from __future__ import annotations

from enum import StrEnum


class JobState(StrEnum):
    PENDENTE = "PENDENTE"
    VALIDANDO_DADOS = "VALIDANDO_DADOS"
    IMPORTANDO_MODELO = "IMPORTANDO_MODELO"
    PREENCHENDO_IDENTIFICACAO = "PREENCHENDO_IDENTIFICACAO"
    SALVANDO_PARAMETROS = "SALVANDO_PARAMETROS"
    REGERANDO_VERBAS = "REGERANDO_VERBAS"
    REGERANDO_FGTS = "REGERANDO_FGTS"
    REGERANDO_CONTRIBUICAO_SOCIAL = "REGERANDO_CONTRIBUICAO_SOCIAL"
    PREENCHENDO_HISTORICO = "PREENCHENDO_HISTORICO"
    LIQUIDANDO = "LIQUIDANDO"
    GERANDO_PDF = "GERANDO_PDF"
    EXPORTANDO_PJC = "EXPORTANDO_PJC"
    VALIDANDO_SAIDAS = "VALIDANDO_SAIDAS"
    CONCLUIDO = "CONCLUIDO"
    ERRO = "ERRO"
